### ISSUE TITLE
What's residual forces?

### ISSUE THREAD

**Issue by jiangzong** [AnyBody/GRF-prediction#4]

**Comment by melund** [comment]
@jiangzong Sorry, for the slow reply. I completely missed your question here. I suggest you ask this kind of questions on http://forum.anyscript.org/

To give you a quick answer here. Residual forces are forces which are added to make the model dynamically balanced. For models without the GRF prediction, the residual forces are reaction-forces which balance the difference between the forces measured by the force plate, and the forces from the model due to gravity etc. These may not match. For example, if the masses or kinematics of the model are inaccurate, or if, for example, the upper body in the model is not included. 

For GRF prediction, we can't just use reaction forces, because the model is supposed to use the conditional contact points under the feet to keep its balance. This is also why GRF prediction needs a full body model, with accurate kinematics. However, to make sure the analysis doesn't fail if the model is somehow out of balance we also add some residual forces to the GRF prediction model.  Here, the residual forces are implemented as very weak recruitment actuators between pelvis and ground. The recruitment actuators behave a little like muscles in the analysis, but since they are the very week the will not be used unless there are no other ways for the model to be dynamically stable. 

You can find more on residual forces GRF prediction in these papers: 
https://link.springer.com/article/10.1007%2Fs11044-016-9537-4
http://www.mdpi.com/1424-8220/17/1/75

**Comment by jiangzong** [comment]
@melund Thank you very much for your reply!
